sonar.projectKey=fabriciorams_proyecto-si783-2026-i-u2-auditoria-bd
sonar.organization=fabriciorams

# Directorios a analizar
sonar.sources=.
sonar.exclusions=**/tests/**, **/__pycache__/**, **/.venv/**, **/.github/**

# Configuración de Python
sonar.python.version=3.10
